name: PR 제출 시 코드 검사 및 SonarQube 분석 실행

on:
    pull_request:
        branches:
            - main
            - develop

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: 코드 체크아웃
              uses: actions/checkout@v2

            - name: JDK 17 설정
              uses: actions/setup-java@v2
              with:
                  distribution: 'temurin'
                  java-version: '17'

            - name: Gradle 패키지 캐싱
              uses: actions/cache@v2
              with:
                  path: |
                      ~/.gradle/caches
                      ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                  restore-keys: |
                      ${{ runner.os }}-gradle-

            - name: ktlint 검사 실행
              run: ./gradlew ktlintCheck

            - name: SonarQube BaseURL 삽입
              run: |
                echo "sonar.coverage.jacoco.xmlReportPaths=$(pwd)/build/reports/jacoco/test/jacocoTestReport.xml" >> sonar-project.properties
                echo "sonar.projectKey=${{secrets.SONARQUBE_PROJECT_KEY}}" >> sonar-project.properties
                echo "sonar.core.serverBaseURL=${{ secrets.SONARQUBE_EC2_HOST }}" >> sonar-project.properties

            - name: sonar-project.properties 파일 내용 확인
              run: |
                  grep "sonar.coverage.jacoco.xmlReportPaths" sonar-project.properties
                  grep "sonar.projectKey" sonar-project.properties
                  grep "sonar.core.serverBaseURL" sonar-project.properties

            - name: SonarQube 분석 실행 후 PR Commant 작성
              uses: sonarsource/sonarqube-scan-action@master
              env:
                  SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
                  SONAR_HOST_URL: ${{ secrets.SONARQUBE_EC2_HOST }}
